# Generated by Django 4.1.7 on 2023-05-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountantreport",
            name="total_current_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="accountantreport",
            name="total_entry_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="accountantreport",
            name="total_output_value",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="accountantreport",
            name="total_previous_value",
            field=models.FloatField(default=0.0),
        ),
    ]
