# Generated by Django 4.1.7 on 2023-06-05 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0002_alter_accountantreport_options_and_more"),
        ("stock", "0002_alter_accountantreport_total_current_value_and_more"),
    ]

    operations = []
