# Generated by Django 4.1.7 on 2023-06-06 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("stock", "0004_alter_dispatchreport_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="end_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="protocol",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
