version: "3.8"

services:
  db:
    image: postgres:13
    container_name: SIRI_DATABASE
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=SIRI_BACK
      - POSTGRES_PASSWORD=SCR@01090!qwer
      - POSTGRES_DB=SIRI_DB_LOCAL
    restart: always


  redis:
    image: redis:latest
    container_name: SIRI_REDIS
    ports:
      - "6379:6379"
    restart: always

  celery:
    build: .
    container_name: SIRI_CELERY
    command: celery -A SIRI_BACK.celery worker -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: always

  celerybeat:
    build: .
    container_name: SIRI_CELERYBEAT
    command: celery -A SIRI_BACK.celery beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: always
  
  web:
    build: .
    container_name: SIRI_SERVER
    command: sh -c "
      python manage.py makemigrations user &&
      python manage.py makemigrations order &&
      python manage.py makemigrations stock &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    restart: always