# Generated by Django 4.1.7 on 2023-05-30 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="client",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="client",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
