# Generated by Django 4.1.7 on 2023-05-29 19:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="materialsorder",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="protocolwithdrawal",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="stockentry",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="stockwithdrawal",
            options={"ordering": ("-created",)},
        ),
        migrations.AlterModelOptions(
            name="supplierorderitem",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="orderitem",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="protocolwithdrawal",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="protocolwithdrawal",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stockentry",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stockentry",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stockwithdrawal",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="stockwithdrawal",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="supplierorderitem",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="supplierorderitem",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
