# Generated by Django 4.1.7 on 2023-05-30 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_materialsorder_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialsorder",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="materialsorder",
            name="updated",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
