# Generated by Django 4.1.7 on 2023-06-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_materialsorder_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialsorder",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="materialsorder",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
