# Generated by Django 4.1.7 on 2023-06-02 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_materialsorder_created_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protocolwithdrawal",
            options={},
        ),
    ]
