# Generated by Django 4.1.7 on 2023-06-02 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_alter_protocolwithdrawal_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="protocolwithdrawal",
            options={"ordering": ("-created",)},
        ),
    ]
