# Generated by Django 4.1.7 on 2023-06-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0005_stockentry_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="file",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
